Feature school controler
ADFC-Hamburg/adfc-radschulwegplan-backend pull request #12
Opened 2018-03-24 15:02 UTC by tabacha

Fixes #9

2018-03-25 14:33 UTC, jetwell requested changes
* The empty constructors in BaseEntity and School can be deleted (unless the framework requires them for some magic)
* The field $logger in SchoolController must be declared above the constructor (maybe also include PHPDoc '@var').
* The Swagger-Documentation is great. Is it possible to include PHPDocs (e.g. '@param' and '@return') in the documentation blocks too? Or would that cause problems?
* We haven't discussed code style issues such as camel case. In my opinion the variables 'singleresult' and 'postalcode' are easier to read if written in camel case: 'singleResult' and 'PostalCode'. If you prefer the current style then that's OK too.
* I fixed minor formatting issues (newlines and spaces).
* Your test method in SchoolControllerTest contains series of tests in a single method. Is is possible to break these down into multiple test methods? You could then give the methods descriptive names like 'testForbiddenForStudentAccount'. It's generally easier to maintain test suites with lots of small tests.

2018-03-26 09:02 UTC, tabacha commented
> * The empty constructors in BaseEntity and School can be deleted (unless the framework requires them for some magic)

are required for doctrine

> * The field $logger in SchoolController must be declared above the constructor (maybe also include PHPDoc '@var').

done

> * The Swagger-Documentation is great. Is it possible to include PHPDocs (e.g. '@param' and '@return') in the documentation blocks too? Or would that cause problems?

we can mix them. I have tried to add phpdocs

> * We haven't discussed code style issues such as camel case. In my opinion the variables 'singleresult' and 'postalcode' are easier to read if written in camel case: 'singleResult' and 'PostalCode'. If you prefer the current style then that's OK too.

i like camelCase

> * I fixed minor formatting issues (newlines and spaces).

thank you

> * Your test method in SchoolControllerTest contains series of tests in a single method. Is is possible to break these down into multiple test methods? You could then give the methods descriptive names like 'testForbiddenForStudentAccount'. It's generally easier to maintain test suites with lots of small tests.

I have split it. But I have a problem with that: The tests are now depends on each other. I have learned, that every test schould work standalone. How do we deal about that? Sadly I found no posibility to load fixtures before each test.

2018-03-28 21:21 UTC, jetwell approved these changes

2018-03-28 21:25 UTC, jetwell commented
I would leave the tests as they are for now. It looks like the test file itself could be split into multiple files. Then the dependencies could be removed by introducing setups and teardowns for groups of similar tests. But we can do that when we next refactor the code.

2018-03-28 21:26 UTC, merged